##########################################################
# GOscore Analysis
# main.R
# 
# Entry point script to run the GOscore pipeline on example data.
# Loads dependencies, sources analysis functions, and executes workflow.
#
# Author: Lu Chen

##########################################################
source("requirements.R")
source("scripts/01_data_preparation.R")
source("scripts/02_GO_enrichment.R")
source("scripts/03_GO_matrix_building.R")
source("scripts/04_GOscore_analysis.R")

# Step 1: Load expression data
expr_data <- load_expression_matrix("data/example_counts.csv")

# Step 2: Convert to ENTREZ IDs
entrez_ids <- convert_to_entrez(expr_data)

# Step 3: Run GO enrichment
go_results <- run_GO_enrichment(entrez_ids)

# Step 4: Build gene-GO matrix
go_matrix_list <- build_GO_matrix(go_results, exprr_data)

# Step 5: Run GOscore analysis
num_timepoints <- ncol(expr_data)
go_score_result <-  run_GOscore_analysis(go_matrix_list,go_start_index = num_timepoints + 1)

# Step 6: Save output
write.csv(go_score_result, file = "output/GOscore_results.csv", row.names = FALSE)

### Downstream analysis (optional)
The GOscore tables generated by this pipeline can be further explored using external tools 
such as KOBAS-i (secondary enrichment), cirFunMap (functional module clustering), or manual 
annotation with QuickGO. Visualization (e.g., –log10(p value) scatterplots) can also be done 
in Excel or R.
